### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by PowerPress** [bluscreenofjeff/CCDC-Scripts#2]
On https://github.com/bluscreenofjeff/CCDC-Scripts/blob/master/OpsPlan2016.txt what do the following nmap options mean -sP -PI?

**Comment by bluscreenofjeff** [comment]
-sP is the equivalent of -sn (no port scan) now; I must have written that down before the option changed
-PI configures nmap to only perform a ping sweep

Looks like the options aren't all covered in the documentation; however, they are listed in the [nmap Mind Map](https://nmap.org/docs/nmap-mindmap.pdf)
